#OperatorReplicaCount
replicas: 1

#namespace
namespace: ""

#mongosReplsets
replsets : 1

#nodeSelector&tolerations
nodeSelector:
  # mongodb: "true"
tolerations: 
  # - key: "mongodb"
  #   operator: "Equal"
  #   value: "true"
  #   effect: "NoSchedule"

#resources
resources:
  limits:
    cpu: "300m"
    memory: "0.5G"
  requests:
    cpu: "100m"
    memory: "0.5G"

#bacukupConfig
backup:
  enabled: true  
  s3:
    bucket: accuknox-mongodb-backup
    region: us-east-2
    prefix: "MongoDB-daily"
